version: '3.7'

services:
  postgresql:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: development
      POSTGRES_PASSWORD: development
      POSTGRES_DB: development
    ports:
      - '5432:5432'
