/* tslint:disable */
/* eslint-disable */
/**
 * Backend BoilerPlate
 * An example NodeJS express project used for bootstrapping services
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@simonball.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { User } from './User';
import {
    UserFromJSON,
    UserFromJSONTyped,
    UserToJSON,
} from './User';

/**
 * 
 * @export
 * @interface LoginPost200Response
 */
export interface LoginPost200Response {
    /**
     * 
     * @type {string}
     * @memberof LoginPost200Response
     */
    message?: string;
    /**
     * 
     * @type {Array<User>}
     * @memberof LoginPost200Response
     */
    data?: Array<User>;
}

/**
 * Check if a given object implements the LoginPost200Response interface.
 */
export function instanceOfLoginPost200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function LoginPost200ResponseFromJSON(json: any): LoginPost200Response {
    return LoginPost200ResponseFromJSONTyped(json, false);
}

export function LoginPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginPost200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': !exists(json, 'message') ? undefined : json['message'],
        'data': !exists(json, 'data') ? undefined : ((json['data'] as Array<any>).map(UserFromJSON)),
    };
}

export function LoginPost200ResponseToJSON(value?: LoginPost200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
        'data': value.data === undefined ? undefined : ((value.data as Array<any>).map(UserToJSON)),
    };
}

