/* tslint:disable */
/* eslint-disable */
/**
 * Backend BoilerPlate
 * An example NodeJS express project used for bootstrapping services
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: contact@simonball.me
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserBasic
 */
export interface UserBasic {
    /**
     * 
     * @type {string}
     * @memberof UserBasic
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof UserBasic
     */
    password?: string;
}

/**
 * Check if a given object implements the UserBasic interface.
 */
export function instanceOfUserBasic(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserBasicFromJSON(json: any): UserBasic {
    return UserBasicFromJSONTyped(json, false);
}

export function UserBasicFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserBasic {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': !exists(json, 'email') ? undefined : json['email'],
        'password': !exists(json, 'password') ? undefined : json['password'],
    };
}

export function UserBasicToJSON(value?: UserBasic | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'password': value.password,
    };
}

